name: Feature request
description: Help us improve our program
title: "[Feature]"
labels:
  - help wanted
  - new_fuction
assignees:
  - qingchenyouforcc
body:
  - type: markdown
    attributes:
      value: |
        请描述你希望实现的功能或改进点：

  - type: textarea
    id: feature_description
    attributes:
      label: 功能描述
      description: 简洁说明新增功能或改进方向
      placeholder: 例如：希望新增“批量下载”功能，支持一次性下载多个链接
    validations:
      required: true

  - type: textarea
    id: usage_scenario
    attributes:
      label: 使用场景
      description: 描述该功能将如何被使用
      placeholder: 例如：我经常需要一次性下载一个歌单里的所有歌曲
    validations:
      required: true

  - type: textarea
    id: solution_optional
    attributes:
      label: 解决方案（可选）
      description: 如果有明确思路或实现方案，请附上
      placeholder: 例如：增加一个“批量导入链接”的输入框，并显示下载队列
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: 优先级建议
      description: 低/中/高（根据相关性或紧急程度）
      options:
        - 低
        - 中
        - 高
    validations:
      required: true

  - type: textarea
    id: other_problem_description
    attributes:
      label: 其他 / 问题描述
      description: 如果与上述类型均不匹配，请直接描述问题（清晰完整地描述你的疑问或需求）
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ### 感谢遵守模板！
        优秀的 Issue 提交能够显著提升协作效率。
        如果填表时遇到困难，请在评论中说明，我们会尽力帮助！
